<a href="https://colab.research.google.com/github/RoshanKumar854/ML-Projects/blob/main/Coursera_2_week_1_variables%2B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
strings = tf.Variable(['Hello world'], tf.string)
floats = tf.Variable([3.14159, 2.71828], tf.float64)
ints = tf.Variable([1, 2, 3], tf.int32)
complexs = tf.Variable([25.9 - 7.39j], 1.23-4.91j, tf.complex128)

In [3]:
tf.Variable(tf.constant(4.2, shape=(3, 3)))

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2]], dtype=float32)>

In [4]:
v = tf.Variable(0.0)
w = v+1

print(type(w))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [5]:
v.assign_add(1)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


In [6]:
v.assign_sub(1)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>


In [7]:
X = tf.constant([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
print(X)
print('dtype:', X.dtype)
print('shape:', X.shape)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
dtype: <dtype: 'int32'>
shape: (3, 3)


In [8]:
X.numpy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [9]:
X = tf.constant([[1, 2, 3], [4, 5, 6],[7, 8, 9]], dtype=tf.float32)
print(X.dtype)

<dtype: 'float32'>


In [10]:
coeffs = np.arange(16)
print(coeffs)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [11]:
shape1 = [8, 2]
shape2 = [4, 4]
shape3 = [2, 2, 2, 2]

In [12]:
a = tf.constant(coeffs, shape=shape1)
print('\n a:\n', a)
b = tf.constant(coeffs, shape=shape2)
print('\n b:\n', b)
c = tf.constant(coeffs, shape=shape3)
print('\n c:\n', c)


 a:
 tf.Tensor(
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]], shape=(8, 2), dtype=int64)

 b:
 tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int64)

 c:
 tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]], shape=(2, 2, 2, 2), dtype=int64)


In [13]:
t = tf.constant(np.arange(80), shape=[5, 2, 8])
print(t)

tf.Tensor(
[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]]

 [[16 17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30 31]]

 [[32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47]]

 [[48 49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62 63]]

 [[64 65 66 67 68 69 70 71]
  [72 73 74 75 76 77 78 79]]], shape=(5, 2, 8), dtype=int64)


In [14]:
rank = tf.rank(t)
print('rank:',rank)

rank: tf.Tensor(3, shape=(), dtype=int32)


In [15]:
t2 = tf.reshape(t, [8,10])


In [16]:
ones = tf.ones(shape=(2,3))
zeros = tf.zeros(shape=(2,4))
eye = tf.eye(3)
tensor7 = tf.constant(7.0, shape=[2, 2])

print('\n ones:\n', ones)
print('\n zeros:\n', zeros)
print('\n eye:\n', eye)
print('\n tensor7:\n', tensor7)


 ones:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)

 zeros:
 tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float32)

 eye:
 tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)

 tensor7:
 tf.Tensor(
[[7. 7.]
 [7. 7.]], shape=(2, 2), dtype=float32)


In [17]:
t1 = tf.ones(shape=(2, 2))
t2 = tf.zeros(shape=(2, 2))

In [18]:
concat0 = tf.concat([t1, t2], 0)
concat1 = tf.concat([t1, t2], 1)



In [19]:
print(concat0)
print(concat1)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]], shape=(2, 4), dtype=float32)


In [20]:
t = tf.constant(np.arange(24), shape=(3, 2, 4))
print('t shape:', t.shape)

t shape: (3, 2, 4)


In [21]:
t1 = tf.expand_dims(t, 0)
t2 = tf.expand_dims(t, 1)
t3 = tf.expand_dims(t, 3)

print('after expanding dims:')
print('t1 shape:', t1.shape)
print('t2 shape:', t2.shape)
print('t3 shape:', t3.shape)

after expanding dims:
t1 shape: (1, 3, 2, 4)
t2 shape: (3, 1, 2, 4)
t3 shape: (3, 2, 4, 1)


In [29]:
X = tf.constant([1, 2, 3, 4, 5, 6, 7])
print(X[1:4])

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [30]:
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
d = tf.constant([[1.0, 1.0], [0.0, 1.0]])

In [33]:
matmul_cd = tf.matmul(c, d)
print(matmul_cd)

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)


In [35]:
c_times_d = c*d
c_plus_d = c+d
c_minus_d = c-d

In [36]:
print(c_times_d)

tf.Tensor(
[[1. 2.]
 [0. 4.]], shape=(2, 2), dtype=float32)
