<a href="https://colab.research.google.com/github/RoshanKumar854/ML-Projects/blob/main/ML_Practice_Ch8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PCA

In [1]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
list(iris.keys())
['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename']

X = iris["data"][:,:]
y = (iris["target"]).astype(np.int) 

In [2]:
X_centered =X-X.mean(axis=0)
U, x, Vt = np.linalg.svd(X_centered)
c1 = Vt.T[:, 0]
c2 = Vt.T[:, 1]
c3 = Vt.T[:, 2]
c4 = Vt.T[:, 3]

In [3]:
W2 = Vt.T[:, :4]
X2D = X_centered.dot(W2)

print(X2D)

[[-2.68412563e+00 -3.19397247e-01  2.79148276e-02  2.26243707e-03]
 [-2.71414169e+00  1.77001225e-01  2.10464272e-01  9.90265503e-02]
 [-2.88899057e+00  1.44949426e-01 -1.79002563e-02  1.99683897e-02]
 [-2.74534286e+00  3.18298979e-01 -3.15593736e-02 -7.55758166e-02]
 [-2.72871654e+00 -3.26754513e-01 -9.00792406e-02 -6.12585926e-02]
 [-2.28085963e+00 -7.41330449e-01 -1.68677658e-01 -2.42008576e-02]
 [-2.82053775e+00  8.94613845e-02 -2.57892158e-01 -4.81431065e-02]
 [-2.62614497e+00 -1.63384960e-01  2.18793179e-02 -4.52978706e-02]
 [-2.88638273e+00  5.78311754e-01 -2.07595703e-02 -2.67447358e-02]
 [-2.67275580e+00  1.13774246e-01  1.97632725e-01 -5.62954013e-02]
 [-2.50694709e+00 -6.45068899e-01  7.53180094e-02 -1.50199245e-02]
 [-2.61275523e+00 -1.47299392e-02 -1.02150260e-01 -1.56379208e-01]
 [-2.78610927e+00  2.35112000e-01  2.06844430e-01 -7.88791149e-03]
 [-3.22380374e+00  5.11394587e-01 -6.12996725e-02 -2.16798118e-02]
 [-2.64475039e+00 -1.17876464e+00  1.51627524e-01  1.59209718e

In [4]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)
X2D = pca.fit_transform(X)

In [5]:
pca.components_.T[:, 0]

array([ 0.36138659, -0.08452251,  0.85667061,  0.3582892 ])

In [6]:
pca.explained_variance_ratio_

array([0.92461872, 0.05306648])

In [7]:
pca = PCA(n_components=0.95)
X_reduced = pca.fit_transform(X)

In [1]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1)
mnist.keys()
X, y = mnist["data"], mnist["target"]
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]



In [9]:
rnd_pca = PCA(n_components=154, svd_solver="randomized")
X_reduced = rnd_pca.fit_transform(X_train)

X_reduced

array([[ 123.93258866, -312.67426201,  -24.51405177, ...,   64.85158336,
         -18.01621876,   33.43757747],
       [1011.71837587, -294.8570382 ,  596.33956108, ...,  -29.94709172,
          31.93552493,  -83.12180288],
       [ -51.84960804,  392.17315293, -188.50974946, ...,  -25.41292495,
          -9.97313035,  -84.71682266],
       ...,
       [-178.0534496 ,  160.07821106, -257.61308215, ...,   58.60931531,
          25.71417629,   -9.13097267],
       [ 130.60607207,   -5.59193643,  513.85867405, ...,   26.69981903,
          83.58268106,  -64.82622595],
       [-173.43595245,  -24.71880229,  556.01889398, ...,   16.61468198,
          -2.05563717,  -82.60234559]])

In [10]:
from sklearn.decomposition import IncrementalPCA

n_batches = 100
inc_pca = IncrementalPCA(n_components=154)
for X_batch in np.array_split(X_train, n_batches):
  inc_pca.partial_fit(X_batch)

X_reduced = inc_pca.transform(X_train) 


#Kernel PCA

In [4]:
from sklearn.decomposition import KernelPCA
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1)
mnist.keys()
X, y = mnist["data"], mnist["target"]
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]

#Selecting a kernel and Tuning Hyperparameters

In [3]:
from sklearn.decomposition import KernelPCA
rbf_pca = KernelPCA(n_components =2, kernel='rbf', gamma=0.0433,
                    fit_inverse_transform=True)
X_reduced = rbf_pca.fit_transform(X)
X_preimage = rbf_pca.inverse_transform(X_reduced)

NameError: ignored

#LLE

In [ ]:
from sklearn.manifold import LocallyLinearEmbedding
lle = LocallyLinearEmbedding(n_components=2, n_neighbors=10)
X_reduced = lle.fit_transform(X)
